### ISSUE TITLE
_socket is not defined

### ISSUE THREAD

**Issue by PaoloTK** [janecker/goxlr-interface#3]
When I assign a hotkey and press it I get a Javascript error:

`Uncaught Exception:
ReferenceError: _socket is not defined
    at Function.<anonymous> (C:\GoXLR Interface\main.js:83:13)`

I am able to get around the issue by commenting out all lines with "_socket" in them. After that when I press the hotkeys I get the correct sound, however in the node console I get a "hotkey registration failed for CTRL+2" message and the routing table doesn't change.

**Comment by janecker** [comment]
Hi @PaoloTK,

I just checked this issue and may have an idea what is going on. First of I pushed a new version with a bit more checking of the settings that should prevent a few error messages and exceptions. Could it be that you did not specify your GoXLR plugin path correctly? The _socket variable was only initialized in case the GoXLR plugin established a connection to the GoXLR interface. In this case GoXLR is not able to change any settings in your GoXLR App.

The latest version will give an error instead of thorwing an excpetion. Could you please check out this new version and also check the path to your GoXRL Plugin executable? Also make sure to to let GoXLR interface restart your GoXLR app before using a hotkey (or do it by hand!).

**Comment by PaoloTK** [comment]
I'm thinking that maybe the issue was caused by the fact that I extracted the executable alone from the plugin without the other files, but I now realize that there's some js stuff in there (at first I thought it was only icons). The reason I didn't extract everything in the first place was that 7zip gave me errors - it thinks there are files named like the folders and so extracting everything fails. 

I have now updated to the latest version and I don't get the error anymore, but instead, I'm getting a "Can't execute action, GoXLR plugin not connected!" error. I've restarted the GoXLR app multiple times, restarted GoXLR Interface, reset the settings for it (deleted the folder in Roaming) and restarted my PC.

**Comment by janecker** [comment]
As far as I know, it should be sufficient to just extract the *.exe. The error you get indicates that for for some reason to GoXRL App is not connected to GoXLR Interface. Have you double checked that you have selected the correct executables for "GoXLR plugin executable" and "GoXLR executable" in GoXLR interface? Do you see the error "Plugin executable not found!"?

Another question? Do you run the Streamdeck software?

**Comment by PaoloTK** [comment]
Yes, the path for both the plugin and program Exe is correct. 

I don't see the error you mentioned but in the terminal I see this:

"(node:9344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)"

I do run the Streamdeck Software but I've also tried closing it and restarting everything - no luck.

**Comment by janecker** [comment]
Hmm, is there any additional information where the exception is thrown? I am not sure what impact the Streamdeck applicaiton can have on everything. Have you checked in that really nothing from elgato was still running? (maybe there is some background process?). I fear it will most likely not be possible to run GoXLR-Interface together with the streamdeck software...

**Comment by PaoloTK** [comment]
> Hmm, is there any additional information where the exception is thrown? I am not sure what impact the Streamdeck applicaiton can have on everything. Have you checked in that really nothing from elgato was still running? (maybe there is some background process?).

Not as far as I can tell. 

I was also not encountering this problem before the last update no matter if the Stream Deck app was running or not. I could trigger hotkeys and hear the sound GoXLR Interface is supposed to play when toggling the routing options.

**Comment by janecker** [comment]
But actually changeing the routing table never worked right? And you do NOT see the message "GoXLR Plugin connected", correct?

That you could hear the sounds only means that the mapping of the hotkey worked, but before the last update GoXLR did not actually check if the plugin is connected or not. This is now done, so you should no longer hear the sounds.

What you could try: run GoXLR interface and then start the GoXLR plugin by hand via the command line. Naviagate to the folder an run:

`[exename] -port 3001 -pluginUUID com.tchelicon.goxlr.routingtable -registerEvent registerEvent -info {}`

Port 3001 is only the default port, if this port is already used, it may use another port. To figure out which port is actually used you can add a debug print at the beginning of the function startWebsocket() in line 32:

`console.log("Starting websocket on port "+port);`

Check if there is any error when starting the plugin by hand and if you see the message "GoXLR Plugin connected".

**Comment by PaoloTK** [comment]
I was able to get rid of that error I got earlier. To reset the settings when I was testing I deleted the folder in Appdata/Roaming, and after that when I launched GoXLR Interface "OBS Websocket address" and "OBS Websocket Port" defaulted to "undefined". This caused some issues and the webserver wasn't starting at all: I couldn't even see the message you made me add to the log. Replacing the address and port with 127.0.0.1 and 4444 respectively got rid of the errors and it looks like the plugin websocket started correctly. 

Everything seems to be working fine now!

**Comment by janecker** [comment]
That is good news! I will try to make the App more resiliant to these types of input errors with the next version. What would be very interesting to me: is it working for you if the Streamdeck software is running? And if so: do both Apps work or only one of them?

**Comment by PaoloTK** [comment]
There seems to be some issues with the Stream Deck software and GoXLR Interface running at the same time. I was able to keep GoXLR Interface working after closing the Stream Deck app, manually starting the plugin with the command you gave me earlier and then opening the Stream Deck app again. However the GoXLR integration wasn't working on the Stream Deck. For me that's not a big issue since I don't plan to use the GoXLR integration on the Stream Deck and would rather have a quick way to mute myself with a mouse button rather than having to press a button on the GoXLR device.
